apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: politicas
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kdvops/politicas.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: politicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
